services:
  - type: web
    name: CruxEn-Flask-Backend
    env: python
    plan: free
    branch: main
    root: .
    buildCommand: "pip install -r flask_app/requirements.txt"
    startCommand: "cd flask_app && gunicorn app:app --bind 0.0.0.0:$PORT"
    envVars:
      - key: GROQ_API_KEY
        fromDeploySecret: GROQ_API_KEY
